apiVersion: validation.spectrocloud.labs/v1alpha1
kind: MaasValidator
metadata:
  name: maasvalidator-sample
spec:
  host: "http://maas.sc:5240/MAAS"
  auth:
    # You have to specify credentials secret
    secretName: maas-creds
    tokenKey: "MAAS_API_KEY"
  imageRules:  
    - name: "OS Rule 1"
      images:
        - name: ubuntu/focal
          architecture: amd64/ga-20.04
        - name: ubuntu/jammy
          architecture: amd64/ga-22.04
    - name: "OS Rule 2"
      images:
        - name: ubuntu/focal
          architecture: amd64/ga-22.04
