apiVersion: validation.spectrocloud.labs/v1alpha1
kind: MaasValidator
metadata:
  name: maasvalidator-sample
spec:
  host: "http://maas.sc:5240/MAAS"
  auth:
    secretName: maas-creds
    tokenKey: "MAAS_API_KEY"
  internalDNSRules:
    - maasDomain: "maas.sc"
      dnsResources:
        - fqdn: "am-ubuntu-0c36d8.maas.sc"
          dnsRecords:
          - type: "A"
            ip: "10.11.130.176"
            ttl: 10
          - type: "A"
            ip: "10.11.130.183"
            ttl: 10
    - maasDomain: "maas.sc"
      dnsResources:
        - fqdn: "am-ubuntu-0c36d8.maas.sc"
          dnsRecords:
          - type: "A"
            ip: "10.11.130.176"
            ttl: 10
          - type: "A"
            ip: "10.11.130.183"
            ttl: 10
          - type: "A"
            ip: "10.11.130.192"
            ttl: 10
          - type: "A"
            ip: "10.11.130.193"
            ttl: 10
  upstreamDNSRules:
    - name: "Upstream DNS Rule 1"
      numDNSServers: 1