apiVersion: validation.spectrocloud.labs/v1alpha1
kind: MaasValidator
metadata:
  name: maasvalidator-sample
spec:
  host: "http://maas.sc:5240/MAAS"
  auth:
    # You have to specify credentials secret
    secretName: maas-credentials
  osImageRules:
    - name: "OS Rule 1"
      osImages:
        - osName: ubuntu/focal
          osArch: amd64/ga-20.04
      
