name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  call-test:
    uses: validator-labs/workflows/.github/workflows/test.yaml@67d5462d2d0a07b1682448d82812397eea892093
    secrets: inherit
