name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  call-test:
    uses: validator-labs/workflows/.github/workflows/test.yaml@b9e4d708ad863b844fe4e0b777a80ad14000e6f8
    secrets: inherit
