name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  call-test:
    uses: validator-labs/workflows/.github/workflows/test.yaml@28b57754dc8ddb5a3e4a5fb7e92a9a0b87f31efe
    secrets: inherit
